import Foundation

/// 단어 예문 한 쌍: 일본어 짧은 문장과 한국어 번역.
public struct ExampleSentence: Sendable, Equatable {
    public let japanese: String
    /// 번역(없으면 표시하지 않는다 — 폴백 예문 등).
    public let korean: String?

    public init(japanese: String, korean: String? = nil) {
        self.japanese = japanese
        self.korean = korean
    }
}

/// 단어별 짧은 예문 모음. 주로 일상회화·여행에서 바로 쓰는 짧은 문장으로 채웠다.
/// 큐레이션된 단어가 없으면 어떤 표기든 문법적으로 성립하는 폴백 예문을 만든다.
public enum ExampleSentenceBank {

    /// 단어 표기로 예문을 찾는다. 큐레이션된 게 없으면 안전한 폴백 예문을 돌려준다.
    public static func sentence(forWord word: String) -> ExampleSentence {
        if let curated = table[word] {
            return curated
        }
        // Tatoeba 한-일 실제 용례(큐레이션에 없는 단어의 빈자리).
        if let tatoeba = tatoebaExamples[word] {
            return tatoeba
        }
        if let kana = kanaExamples[word] {
            return kana
        }
        // 따옴표로 인용하면 품사와 무관하게 문장이 성립한다.
        return ExampleSentence(japanese: "「\(word)」を覚えました。")
    }

    private static let table: [String: ExampleSentence] = [
        // 사람·관계
        "私": .init(japanese: "私は学生です。", korean: "저는 학생이에요."),
        "先生": .init(japanese: "先生に質問します。", korean: "선생님께 질문해요."),
        "学生": .init(japanese: "私は大学の学生です。", korean: "저는 대학생이에요."),
        "友達": .init(japanese: "友達と映画を見ます。", korean: "친구와 영화를 봐요."),
        "家族": .init(japanese: "家族と旅行します。", korean: "가족과 여행해요."),
        "父": .init(japanese: "父は仕事に行きました。", korean: "아버지는 일하러 가셨어요."),
        "母": .init(japanese: "母に電話します。", korean: "어머니께 전화해요."),
        "子供": .init(japanese: "子供が公園で遊んでいます。", korean: "아이가 공원에서 놀고 있어요."),
        "人": .init(japanese: "あの人を知っていますか。", korean: "저 사람 알아요?"),
        "名前": .init(japanese: "お名前は何ですか。", korean: "이름이 뭐예요?"),

        // 시간
        "時間": .init(japanese: "時間がありますか。", korean: "시간 있어요?"),
        "今日": .init(japanese: "今日は何をしますか。", korean: "오늘 뭐 해요?"),
        "明日": .init(japanese: "明日また来ます。", korean: "내일 또 올게요."),
        "昨日": .init(japanese: "昨日は雨でした。", korean: "어제는 비가 왔어요."),
        "毎日": .init(japanese: "毎日日本語を勉強します。", korean: "매일 일본어를 공부해요."),
        "今": .init(japanese: "今何時ですか。", korean: "지금 몇 시예요?"),
        "朝": .init(japanese: "朝ごはんを食べました。", korean: "아침을 먹었어요."),
        "昼": .init(japanese: "昼に出かけます。", korean: "점심때 외출해요."),
        "夜": .init(japanese: "夜は早く寝ます。", korean: "밤에는 일찍 자요."),
        "週末": .init(japanese: "週末は何をしますか。", korean: "주말에 뭐 해요?"),

        // 음식·음료
        "水": .init(japanese: "お水をください。", korean: "물 좀 주세요."),
        "お茶": .init(japanese: "お茶を飲みましょう。", korean: "차 마셔요."),
        "ご飯": .init(japanese: "ご飯を食べましょう。", korean: "밥 먹어요."),
        "肉": .init(japanese: "肉が好きです。", korean: "고기를 좋아해요."),
        "魚": .init(japanese: "魚を食べます。", korean: "생선을 먹어요."),
        "野菜": .init(japanese: "野菜も食べてください。", korean: "채소도 드세요."),
        "果物": .init(japanese: "果物が好きです。", korean: "과일을 좋아해요."),
        "卵": .init(japanese: "卵を二つください。", korean: "달걀 두 개 주세요."),
        "牛乳": .init(japanese: "牛乳を買います。", korean: "우유를 사요."),
        "パン": .init(japanese: "朝はパンを食べます。", korean: "아침엔 빵을 먹어요."),

        // 장소
        "家": .init(japanese: "もう家に帰ります。", korean: "이제 집에 가요."),
        "部屋": .init(japanese: "部屋を予約しました。", korean: "방을 예약했어요."),
        "学校": .init(japanese: "学校へ行きます。", korean: "학교에 가요."),
        "会社": .init(japanese: "会社まで電車で行きます。", korean: "회사까지 전철로 가요."),
        "店": .init(japanese: "あの店に入りましょう。", korean: "저 가게에 들어가요."),
        "駅": .init(japanese: "駅はどこですか。", korean: "역은 어디예요?"),
        "道": .init(japanese: "道を教えてください。", korean: "길을 알려 주세요."),
        "町": .init(japanese: "この町は静かです。", korean: "이 동네는 조용해요."),
        "国": .init(japanese: "お国はどちらですか。", korean: "어느 나라에서 오셨어요?"),
        "山": .init(japanese: "山に登ります。", korean: "산에 올라가요."),
        "川": .init(japanese: "川で泳ぎます。", korean: "강에서 헤엄쳐요."),
        "海": .init(japanese: "海を見に行きます。", korean: "바다를 보러 가요."),
        "空": .init(japanese: "空がきれいです。", korean: "하늘이 예뻐요."),

        // 날씨·자연
        "天気": .init(japanese: "今日はいい天気ですね。", korean: "오늘 날씨 좋네요."),
        "雨": .init(japanese: "雨が降っています。", korean: "비가 와요."),
        "雪": .init(japanese: "雪が降りました。", korean: "눈이 왔어요."),
        "風": .init(japanese: "風が強いです。", korean: "바람이 세요."),
        "犬": .init(japanese: "犬を飼っています。", korean: "개를 키워요."),
        "猫": .init(japanese: "猫がかわいいです。", korean: "고양이가 귀여워요."),
        "鳥": .init(japanese: "鳥が鳴いています。", korean: "새가 울고 있어요."),

        // 사물
        "車": .init(japanese: "車で行きましょう。", korean: "차로 가요."),
        "電話": .init(japanese: "後で電話します。", korean: "나중에 전화할게요."),
        "時計": .init(japanese: "その時計は高いです。", korean: "그 시계는 비싸요."),
        "本": .init(japanese: "本を読みます。", korean: "책을 읽어요."),
        "新聞": .init(japanese: "朝、新聞を読みます。", korean: "아침에 신문을 읽어요."),
        "手紙": .init(japanese: "友達に手紙を書きます。", korean: "친구에게 편지를 써요."),
        "写真": .init(japanese: "写真を撮ってもいいですか。", korean: "사진 찍어도 돼요?"),
        "映画": .init(japanese: "映画を見に行きます。", korean: "영화를 보러 가요."),
        "音楽": .init(japanese: "音楽を聞きます。", korean: "음악을 들어요."),
        "お金": .init(japanese: "お金が足りません。", korean: "돈이 모자라요."),

        // 일상·활동
        "仕事": .init(japanese: "仕事が忙しいです。", korean: "일이 바빠요."),
        "休み": .init(japanese: "明日は休みです。", korean: "내일은 쉬는 날이에요."),
        "旅行": .init(japanese: "日本へ旅行します。", korean: "일본으로 여행해요."),
        "買い物": .init(japanese: "買い物に行きます。", korean: "장 보러 가요."),
        "料理": .init(japanese: "料理を作ります。", korean: "요리를 만들어요."),

        // 동사
        "食べる": .init(japanese: "何を食べますか。", korean: "뭘 드시겠어요?"),
        "飲む": .init(japanese: "何か飲みますか。", korean: "뭐 좀 마실래요?"),
        "行く": .init(japanese: "一緒に行きましょう。", korean: "같이 가요."),
        "来る": .init(japanese: "また来てください。", korean: "또 오세요."),
        "帰る": .init(japanese: "もう帰りますか。", korean: "벌써 가세요?"),
        "見る": .init(japanese: "ちょっと見てもいいですか。", korean: "좀 봐도 돼요?"),
        "聞く": .init(japanese: "道を聞きます。", korean: "길을 물어요."),
        "読む": .init(japanese: "本を読むのが好きです。", korean: "책 읽는 걸 좋아해요."),
        "書く": .init(japanese: "ここに名前を書いてください。", korean: "여기에 이름을 써 주세요."),
        "話す": .init(japanese: "日本語が話せますか。", korean: "일본어 할 수 있어요?"),
        "会う": .init(japanese: "駅で会いましょう。", korean: "역에서 만나요."),
        "買う": .init(japanese: "お土産を買います。", korean: "기념품을 사요."),
        "売る": .init(japanese: "ここで切符を売っていますか。", korean: "여기서 표를 팔아요?"),
        "立つ": .init(japanese: "ここに立ってください。", korean: "여기 서 주세요."),
        "座る": .init(japanese: "どうぞ座ってください。", korean: "앉으세요."),
        "寝る": .init(japanese: "もう寝ます。", korean: "이제 잘게요."),
        "起きる": .init(japanese: "朝六時に起きます。", korean: "아침 6시에 일어나요."),

        // 형용사
        "大きい": .init(japanese: "もっと大きいのはありますか。", korean: "더 큰 거 있어요?"),
        "小さい": .init(japanese: "少し小さいです。", korean: "좀 작아요."),
        "新しい": .init(japanese: "新しいのが欲しいです。", korean: "새것을 원해요."),
        "古い": .init(japanese: "この建物は古いです。", korean: "이 건물은 오래됐어요."),
        "高い": .init(japanese: "ちょっと高いですね。", korean: "좀 비싸네요."),
        "安い": .init(japanese: "これは安いです。", korean: "이건 싸요."),
        "良い": .init(japanese: "それはいいですね。", korean: "그거 좋네요."),
        "悪い": .init(japanese: "体の調子が悪いです。", korean: "몸 상태가 안 좋아요."),
        "暑い": .init(japanese: "今日は暑いです。", korean: "오늘은 더워요."),
        "寒い": .init(japanese: "外は寒いです。", korean: "밖은 추워요."),
        "忙しい": .init(japanese: "今日は忙しいです。", korean: "오늘은 바빠요."),
        "楽しい": .init(japanese: "とても楽しかったです。", korean: "정말 즐거웠어요."),

        // 여행 — 공항·이동
        "空港": .init(japanese: "空港まで行きたいです。", korean: "공항까지 가고 싶어요."),
        "飛行機": .init(japanese: "飛行機の時間に遅れました。", korean: "비행기 시간에 늦었어요."),
        "搭乗券": .init(japanese: "搭乗券を見せてください。", korean: "탑승권을 보여 주세요."),
        "パスポート": .init(japanese: "パスポートをなくしました。", korean: "여권을 잃어버렸어요."),
        "荷物": .init(japanese: "荷物はこれだけです。", korean: "짐은 이게 다예요."),
        "両替": .init(japanese: "両替はどこでできますか。", korean: "환전은 어디서 해요?"),
        "改札": .init(japanese: "改札はどこですか。", korean: "개찰구는 어디예요?"),
        "切符": .init(japanese: "切符を一枚ください。", korean: "표 한 장 주세요."),
        "電車": .init(japanese: "電車に乗り遅れました。", korean: "전철을 놓쳤어요."),
        "新幹線": .init(japanese: "新幹線で大阪へ行きます。", korean: "신칸센으로 오사카에 가요."),
        "地下鉄": .init(japanese: "地下鉄が便利です。", korean: "지하철이 편해요."),
        "バス停": .init(japanese: "バス停はどこですか。", korean: "버스 정류장은 어디예요?"),
        "タクシー": .init(japanese: "タクシーを呼んでください。", korean: "택시를 불러 주세요."),
        "乗り換え": .init(japanese: "どこで乗り換えますか。", korean: "어디서 갈아타요?"),
        "出口": .init(japanese: "出口はどちらですか。", korean: "출구는 어느 쪽이에요?"),
        "入口": .init(japanese: "入口はあちらです。", korean: "입구는 저쪽이에요."),
        "コインロッカー": .init(japanese: "コインロッカーはありますか。", korean: "코인 로커 있어요?"),

        // 여행 — 길찾기
        "右": .init(japanese: "次の角を右に曲がってください。", korean: "다음 모퉁이에서 오른쪽으로 도세요."),
        "左": .init(japanese: "左に見えます。", korean: "왼쪽에 보여요."),
        "まっすぐ": .init(japanese: "まっすぐ行ってください。", korean: "곧장 가세요."),
        "近い": .init(japanese: "駅はここから近いですか。", korean: "역은 여기서 가까워요?"),
        "遠い": .init(japanese: "そこは少し遠いです。", korean: "거기는 좀 멀어요."),

        // 여행 — 숙소
        "予約": .init(japanese: "予約をしたいです。", korean: "예약하고 싶어요."),
        "ホテル": .init(japanese: "ホテルまでお願いします。", korean: "호텔까지 가 주세요."),
        "旅館": .init(japanese: "旅館に泊まります。", korean: "료칸에 묵어요."),
        "温泉": .init(japanese: "温泉に入りたいです。", korean: "온천에 들어가고 싶어요."),
        "鍵": .init(japanese: "部屋の鍵をください。", korean: "방 열쇠 주세요."),
        "フロント": .init(japanese: "フロントで聞いてください。", korean: "프런트에서 물어보세요."),
        "朝食": .init(japanese: "朝食は何時からですか。", korean: "조식은 몇 시부터예요?"),
        "荷物預かり": .init(japanese: "荷物預かりはありますか。", korean: "짐 보관 되나요?"),
        "充電": .init(japanese: "ここで充電できますか。", korean: "여기서 충전할 수 있어요?"),

        // 여행 — 식사·계산
        "食事": .init(japanese: "食事はもう済みました。", korean: "식사는 이미 했어요."),
        "注文": .init(japanese: "注文をお願いします。", korean: "주문할게요."),
        "お会計": .init(japanese: "お会計をお願いします。", korean: "계산해 주세요."),
        "現金": .init(japanese: "現金で払います。", korean: "현금으로 낼게요."),
        "領収書": .init(japanese: "領収書をください。", korean: "영수증 주세요."),
        "お水": .init(japanese: "お水をもう一杯ください。", korean: "물 한 잔 더 주세요."),
        "お湯": .init(japanese: "お湯はありますか。", korean: "뜨거운 물 있어요?"),
        "おすすめ": .init(japanese: "おすすめは何ですか。", korean: "추천 메뉴가 뭐예요?"),
        "美味しい": .init(japanese: "とても美味しいです。", korean: "정말 맛있어요."),
        "居酒屋": .init(japanese: "居酒屋に行きましょう。", korean: "이자카야에 가요."),
        "定食": .init(japanese: "定食をください。", korean: "정식 주세요."),
        "持ち帰り": .init(japanese: "持ち帰りでお願いします。", korean: "포장해 주세요."),

        // 여행 — 쇼핑
        "お土産": .init(japanese: "お土産を買いたいです。", korean: "기념품을 사고 싶어요."),
        "免税": .init(japanese: "免税できますか。", korean: "면세 되나요?"),
        "値段": .init(japanese: "値段はいくらですか。", korean: "가격이 얼마예요?"),
        "無料": .init(japanese: "これは無料ですか。", korean: "이건 무료예요?"),
        "有料": .init(japanese: "Wi-Fiは有料ですか。", korean: "와이파이는 유료예요?"),
        "営業中": .init(japanese: "お店は営業中ですか。", korean: "가게 영업 중이에요?"),
        "定休日": .init(japanese: "定休日はいつですか。", korean: "정기 휴일이 언제예요?"),
        "試着": .init(japanese: "試着してもいいですか。", korean: "입어 봐도 돼요?"),
        "袋": .init(japanese: "袋をください。", korean: "봉투 주세요."),

        // 여행 — 곤란할 때
        "トイレ": .init(japanese: "トイレはどこですか。", korean: "화장실은 어디예요?"),
        "薬局": .init(japanese: "近くに薬局はありますか。", korean: "근처에 약국 있어요?"),
        "病院": .init(japanese: "病院へ行きたいです。", korean: "병원에 가고 싶어요."),
        "警察": .init(japanese: "警察を呼んでください。", korean: "경찰을 불러 주세요."),
        "交番": .init(japanese: "交番はどこですか。", korean: "파출소는 어디예요?"),
        "助けて": .init(japanese: "助けてください！", korean: "도와주세요!"),
        "大丈夫": .init(japanese: "大丈夫ですか。", korean: "괜찮으세요?"),
        "迷子": .init(japanese: "迷子になりました。", korean: "길을 잃었어요."),
        "忘れ物": .init(japanese: "忘れ物をしました。", korean: "물건을 두고 왔어요."),

        // 여행 — 인사·표현
        "すみません": .init(japanese: "すみません、ちょっといいですか。", korean: "저기요, 잠깐 괜찮아요?"),
        "お願いします": .init(japanese: "これをお願いします。", korean: "이거 부탁해요."),
        "いくらですか": .init(japanese: "これはいくらですか。", korean: "이거 얼마예요?"),
        "どこですか": .init(japanese: "出口はどこですか。", korean: "출구는 어디예요?"),
        "分かりません": .init(japanese: "すみません、分かりません。", korean: "죄송해요, 모르겠어요."),
        "日本語": .init(japanese: "日本語が少し話せます。", korean: "일본어를 조금 할 수 있어요."),
        "韓国語": .init(japanese: "韓国語が分かりますか。", korean: "한국어 할 줄 아세요?"),
        "英語": .init(japanese: "英語は話せますか。", korean: "영어 할 수 있어요?"),
    ]

    /// 가나 학습 화면에서 쓰는 예시 단어(가나 표기)용 짧은 문장.
    private static let kanaExamples: [String: ExampleSentence] = [
        // 히라가나 예시 단어
        "あめ": .init(japanese: "今日はあめです。", korean: "오늘은 비가 와요."),
        "いぬ": .init(japanese: "いぬがすきです。", korean: "개를 좋아해요."),
        "うみ": .init(japanese: "うみへ行きます。", korean: "바다에 가요."),
        "えき": .init(japanese: "えきはどこですか。", korean: "역은 어디예요?"),
        "おかね": .init(japanese: "おかねがありません。", korean: "돈이 없어요."),
        "かさ": .init(japanese: "かさを忘れました。", korean: "우산을 잃어버렸어요."),
        "き": .init(japanese: "公園にきがあります。", korean: "공원에 나무가 있어요."),
        "くつ": .init(japanese: "くつを買います。", korean: "신발을 사요."),
        "けさ": .init(japanese: "けさは寒いです。", korean: "오늘 아침은 추워요."),
        "こども": .init(japanese: "こどもがかわいいです。", korean: "아이가 귀여워요."),
        "さかな": .init(japanese: "さかなを食べます。", korean: "생선을 먹어요."),
        "しんぶん": .init(japanese: "しんぶんを読みます。", korean: "신문을 읽어요."),
        "すし": .init(japanese: "すしが食べたいです。", korean: "초밥이 먹고 싶어요."),
        "せんせい": .init(japanese: "せんせいに聞きます。", korean: "선생님께 여쭤봐요."),
        "そら": .init(japanese: "そらがきれいです。", korean: "하늘이 예뻐요."),
        "たまご": .init(japanese: "たまごを買います。", korean: "달걀을 사요."),
        "ちず": .init(japanese: "ちずを見ます。", korean: "지도를 봐요."),
        "つき": .init(japanese: "つきがきれいです。", korean: "달이 예뻐요."),
        "て": .init(japanese: "てを洗います。", korean: "손을 씻어요."),
        "とり": .init(japanese: "とりが飛んでいます。", korean: "새가 날고 있어요."),
        "なつ": .init(japanese: "なつは暑いです。", korean: "여름은 더워요."),
        "にく": .init(japanese: "にくが好きです。", korean: "고기를 좋아해요."),
        "ぬの": .init(japanese: "ぬので作ります。", korean: "천으로 만들어요."),
        "ねこ": .init(japanese: "ねこがすきです。", korean: "고양이를 좋아해요."),
        "のみもの": .init(japanese: "のみものは何がいいですか。", korean: "음료는 뭐가 좋아요?"),
        "はな": .init(japanese: "はながきれいです。", korean: "꽃이 예뻐요."),
        "ひと": .init(japanese: "あのひとは誰ですか。", korean: "저 사람 누구예요?"),
        "ふゆ": .init(japanese: "ふゆは寒いです。", korean: "겨울은 추워요."),
        "へや": .init(japanese: "へやがひろいです。", korean: "방이 넓어요."),
        "ほん": .init(japanese: "ほんを読みます。", korean: "책을 읽어요."),
        "まど": .init(japanese: "まどを開けます。", korean: "창문을 열어요."),
        "みず": .init(japanese: "みずを飲みます。", korean: "물을 마셔요."),
        "むし": .init(japanese: "むしがいます。", korean: "벌레가 있어요."),
        "め": .init(japanese: "めがいたいです。", korean: "눈이 아파요."),
        "もも": .init(japanese: "ももが好きです。", korean: "복숭아를 좋아해요."),
        "やま": .init(japanese: "やまに登ります。", korean: "산에 올라가요."),
        "ゆき": .init(japanese: "ゆきが降ります。", korean: "눈이 와요."),
        "よる": .init(japanese: "よるは静かです。", korean: "밤은 조용해요."),
        "らいねん": .init(japanese: "らいねん日本へ行きます。", korean: "내년에 일본에 가요."),
        "りんご": .init(japanese: "りんごを食べます。", korean: "사과를 먹어요."),
        "るす": .init(japanese: "いま、るすです。", korean: "지금 부재중이에요."),
        "れきし": .init(japanese: "れきしが好きです。", korean: "역사를 좋아해요."),
        "ろく": .init(japanese: "ろく時に起きます。", korean: "6시에 일어나요."),
        "わたし": .init(japanese: "わたしは学生です。", korean: "저는 학생이에요."),
        "ほんをよむ": .init(japanese: "ほんをよむのが好きです。", korean: "책 읽는 걸 좋아해요."),
        "がっこう": .init(japanese: "がっこうへ行きます。", korean: "학교에 가요."),
        "ぎんこう": .init(japanese: "ぎんこうはどこですか。", korean: "은행은 어디예요?"),
        "かぐ": .init(japanese: "あたらしいかぐを買います。", korean: "새 가구를 사요."),
        "げんき": .init(japanese: "おげんきですか。", korean: "잘 지내요?"),
        "ごはん": .init(japanese: "ごはんを食べます。", korean: "밥을 먹어요."),
        "ざっし": .init(japanese: "ざっしを読みます。", korean: "잡지를 읽어요."),
        "じかん": .init(japanese: "じかんがありません。", korean: "시간이 없어요."),
        "かぜ": .init(japanese: "かぜをひきました。", korean: "감기에 걸렸어요."),
        "かぞく": .init(japanese: "かぞくと住んでいます。", korean: "가족과 살아요."),
        "だいがく": .init(japanese: "だいがくの学生です。", korean: "대학생이에요."),
        "はなぢ": .init(japanese: "はなぢが出ました。", korean: "코피가 났어요."),
        "つづく": .init(japanese: "あめがつづきます。", korean: "비가 계속돼요."),
        "でんわ": .init(japanese: "でんわをします。", korean: "전화를 해요."),
        "どようび": .init(japanese: "どようびは休みです。", korean: "토요일은 쉬어요."),
        "かばん": .init(japanese: "かばんを買います。", korean: "가방을 사요."),
        "びょういん": .init(japanese: "びょういんへ行きます。", korean: "병원에 가요."),
        "ぶたにく": .init(japanese: "ぶたにくを食べます。", korean: "돼지고기를 먹어요."),
        "べんきょう": .init(japanese: "にほんごをべんきょうします。", korean: "일본어를 공부해요."),
        "ぼうし": .init(japanese: "ぼうしをかぶります。", korean: "모자를 써요."),
        "いっぱい": .init(japanese: "おなかがいっぱいです。", korean: "배가 불러요."),
        "えんぴつ": .init(japanese: "えんぴつで書きます。", korean: "연필로 써요."),
        "てんぷら": .init(japanese: "てんぷらが好きです。", korean: "튀김을 좋아해요."),
        "ぺこぺこ": .init(japanese: "おなかがぺこぺこです。", korean: "배가 너무 고파요."),
        "さんぽ": .init(japanese: "さんぽに行きます。", korean: "산책하러 가요."),
        "きゃく": .init(japanese: "きゃくが来ます。", korean: "손님이 와요."),
        "きゅう": .init(japanese: "きゅう時に会いましょう。", korean: "9시에 만나요."),
        "きょう": .init(japanese: "きょうは何をしますか。", korean: "오늘 뭐 해요?"),
        "しゃしん": .init(japanese: "しゃしんを撮ります。", korean: "사진을 찍어요."),
        "しゅみ": .init(japanese: "しゅみは何ですか。", korean: "취미가 뭐예요?"),
        "じしょ": .init(japanese: "じしょで調べます。", korean: "사전으로 찾아봐요."),
        "おちゃ": .init(japanese: "おちゃを飲みます。", korean: "차를 마셔요."),
        "ちゅうい": .init(japanese: "ちゅういしてください。", korean: "조심하세요."),
        "ちょっと": .init(japanese: "ちょっと待ってください。", korean: "잠깐 기다려 주세요."),
        "にゅうがく": .init(japanese: "だいがくににゅうがくします。", korean: "대학에 입학해요."),
        "ひゃく": .init(japanese: "ひゃく円です。", korean: "100엔이에요."),
        "じゃま": .init(japanese: "おじゃまします。", korean: "실례하겠습니다."),
        "じゅぎょう": .init(japanese: "じゅぎょうが始まります。", korean: "수업이 시작돼요."),
        "じょせい": .init(japanese: "じょせいに人気です。", korean: "여성에게 인기예요."),
        "しょうりゃく": .init(japanese: "せつめいをしょうりゃくします。", korean: "설명을 생략해요."),
        "りゅうがく": .init(japanese: "にほんにりゅうがくします。", korean: "일본으로 유학 가요."),
        "りょこう": .init(japanese: "りょこうが好きです。", korean: "여행을 좋아해요."),

        // 가타카나 예시 단어
        "アイス": .init(japanese: "アイスを食べます。", korean: "아이스크림을 먹어요."),
        "イス": .init(japanese: "イスに座ります。", korean: "의자에 앉아요."),
        "ウイルス": .init(japanese: "ウイルスに注意してください。", korean: "바이러스를 조심하세요."),
        "エアコン": .init(japanese: "エアコンをつけます。", korean: "에어컨을 켜요."),
        "オレンジ": .init(japanese: "オレンジを買います。", korean: "오렌지를 사요."),
        "カメラ": .init(japanese: "カメラで撮ります。", korean: "카메라로 찍어요."),
        "キムチ": .init(japanese: "キムチが好きです。", korean: "김치를 좋아해요."),
        "クラス": .init(japanese: "クラスがいっしょです。", korean: "같은 반이에요."),
        "ケーキ": .init(japanese: "ケーキを食べます。", korean: "케이크를 먹어요."),
        "コーヒー": .init(japanese: "コーヒーを飲みます。", korean: "커피를 마셔요."),
        "サッカー": .init(japanese: "サッカーをします。", korean: "축구를 해요."),
        "シャツ": .init(japanese: "シャツを買います。", korean: "셔츠를 사요."),
        "スープ": .init(japanese: "スープを飲みます。", korean: "수프를 먹어요."),
        "セーター": .init(japanese: "セーターを着ます。", korean: "스웨터를 입어요."),
        "ソファ": .init(japanese: "ソファに座ります。", korean: "소파에 앉아요."),
        "タクシー": .init(japanese: "タクシーに乗ります。", korean: "택시를 타요."),
        "チーズ": .init(japanese: "チーズが好きです。", korean: "치즈를 좋아해요."),
        "ツアー": .init(japanese: "ツアーに参加します。", korean: "투어에 참가해요."),
        "テレビ": .init(japanese: "テレビを見ます。", korean: "텔레비전을 봐요."),
        "トマト": .init(japanese: "トマトを買います。", korean: "토마토를 사요."),
        "ナイフ": .init(japanese: "ナイフを使います。", korean: "나이프를 써요."),
        "ニュース": .init(japanese: "ニュースを見ます。", korean: "뉴스를 봐요."),
        "ヌードル": .init(japanese: "ヌードルを食べます。", korean: "면을 먹어요."),
        "ネクタイ": .init(japanese: "ネクタイをします。", korean: "넥타이를 매요."),
        "ノート": .init(japanese: "ノートに書きます。", korean: "노트에 써요."),
        "ハンバーガー": .init(japanese: "ハンバーガーを食べます。", korean: "햄버거를 먹어요."),
        "ヒーター": .init(japanese: "ヒーターをつけます。", korean: "히터를 켜요."),
        "フォーク": .init(japanese: "フォークで食べます。", korean: "포크로 먹어요."),
        "ヘア": .init(japanese: "ヘアを切ります。", korean: "머리를 잘라요."),
        "ホテル": .init(japanese: "ホテルに泊まります。", korean: "호텔에 묵어요."),
        "マスク": .init(japanese: "マスクをします。", korean: "마스크를 써요."),
        "ミルク": .init(japanese: "ミルクを飲みます。", korean: "우유를 마셔요."),
        "ムービー": .init(japanese: "ムービーを見ます。", korean: "영상을 봐요."),
        "メール": .init(japanese: "メールを送ります。", korean: "메일을 보내요."),
        "モデル": .init(japanese: "モデルになりたいです。", korean: "모델이 되고 싶어요."),
        "タイヤ": .init(japanese: "タイヤを交換します。", korean: "타이어를 교체해요."),
        "ユーザー": .init(japanese: "ユーザーが多いです。", korean: "사용자가 많아요."),
        "ヨーグルト": .init(japanese: "ヨーグルトを食べます。", korean: "요구르트를 먹어요."),
        "ラーメン": .init(japanese: "ラーメンを食べます。", korean: "라면을 먹어요."),
        "リスト": .init(japanese: "リストを作ります。", korean: "리스트를 만들어요."),
        "ルール": .init(japanese: "ルールを守ります。", korean: "규칙을 지켜요."),
        "レストラン": .init(japanese: "レストランで食べます。", korean: "레스토랑에서 먹어요."),
        "ロボット": .init(japanese: "ロボットが好きです。", korean: "로봇을 좋아해요."),
        "ワイン": .init(japanese: "ワインを飲みます。", korean: "와인을 마셔요."),
        "パン": .init(japanese: "パンを食べます。", korean: "빵을 먹어요."),
        "ガラス": .init(japanese: "ガラスが割れました。", korean: "유리가 깨졌어요."),
        "ギター": .init(japanese: "ギターを弾きます。", korean: "기타를 쳐요."),
        "グラス": .init(japanese: "グラスに水を入れます。", korean: "유리잔에 물을 따라요."),
        "ゲーム": .init(japanese: "ゲームをします。", korean: "게임을 해요."),
        "ゴルフ": .init(japanese: "ゴルフをします。", korean: "골프를 쳐요."),
        "ピザ": .init(japanese: "ピザを食べます。", korean: "피자를 먹어요."),
        "ジュース": .init(japanese: "ジュースを飲みます。", korean: "주스를 마셔요."),
        "ズボン": .init(japanese: "ズボンをはきます。", korean: "바지를 입어요."),
        "ゼロ": .init(japanese: "ゼロから始めます。", korean: "제로부터 시작해요."),
        "ゾーン": .init(japanese: "ここは禁煙ゾーンです。", korean: "여긴 금연 구역이에요."),
        "ダンス": .init(japanese: "ダンスを習います。", korean: "춤을 배워요."),
        "デパート": .init(japanese: "デパートで買います。", korean: "백화점에서 사요."),
        "ドア": .init(japanese: "ドアを開けます。", korean: "문을 열어요."),
        "バス": .init(japanese: "バスに乗ります。", korean: "버스를 타요."),
        "ビール": .init(japanese: "ビールを飲みます。", korean: "맥주를 마셔요."),
        "ブログ": .init(japanese: "ブログを書きます。", korean: "블로그를 써요."),
        "ベッド": .init(japanese: "ベッドで寝ます。", korean: "침대에서 자요."),
        "ボール": .init(japanese: "ボールを投げます。", korean: "공을 던져요."),
        "ピアノ": .init(japanese: "ピアノを弾きます。", korean: "피아노를 쳐요."),
        "プール": .init(japanese: "プールで泳ぎます。", korean: "수영장에서 헤엄쳐요."),
        "ペン": .init(japanese: "ペンで書きます。", korean: "펜으로 써요."),
        "ポケット": .init(japanese: "ポケットに入れます。", korean: "주머니에 넣어요."),
        "キャンプ": .init(japanese: "キャンプに行きます。", korean: "캠핑하러 가요."),
        "バーベキュー": .init(japanese: "バーベキューをします。", korean: "바비큐를 해요."),
        "シューズ": .init(japanese: "シューズを買います。", korean: "신발을 사요."),
        "ショップ": .init(japanese: "ショップに行きます。", korean: "가게에 가요."),
        "チャンス": .init(japanese: "チャンスです。", korean: "기회예요."),
        "チョコ": .init(japanese: "チョコを食べます。", korean: "초콜릿을 먹어요."),
        "ミュージック": .init(japanese: "ミュージックを聞きます。", korean: "음악을 들어요."),
        "リュック": .init(japanese: "リュックを背負います。", korean: "배낭을 메요."),
        "ジャム": .init(japanese: "パンにジャムをぬります。", korean: "빵에 잼을 발라요."),
        "ジョギング": .init(japanese: "ジョギングをします。", korean: "조깅을 해요."),
        "コンピューター": .init(japanese: "コンピューターを使います。", korean: "컴퓨터를 써요."),
    ]
}
