import Foundation

// 자동 생성 — 직접 수정하지 말 것. (Tools/gen_tatoeba_examples.py)
// 예문 출처: Tatoeba Project (https://tatoeba.org) — CC BY 2.0 FR.
// 사람이 번역한 일본어↔한국어 문장쌍에서 추출한 단어별 예문.

/// Tatoeba 예문(단어 표기 → 예문). 큐레이션에 없는 단어의 빈자리를 채운다.
let tatoebaExamples: [String: ExampleSentence] = [
    "お腹": .init(japanese: "お腹が痛いです。", korean: "배가 아파요."),
    "お風呂": .init(japanese: "お風呂には入りましたか。", korean: "너 목욕했니?"),
    "くれる": .init(japanese: "彼は気前よく金を出してくれる。", korean: "그는 마음씨 좋게 돈을 내준다."),
    "予定": .init(japanese: "今晩は予定がある？", korean: "오늘 밤에 해야 하는 일 있어?"),
    "事故": .init(japanese: "事故があった。", korean: "사고가 벌어졌다."),
    "会議": .init(japanese: "会議は明日開かれる。", korean: "회의는 내일 열린다."),
    "住む": .init(japanese: "ボストンって、住むのにいい所？", korean: "보스턴은 살기 좋은 곳이야?"),
    "住所": .init(japanese: "彼の住所を忘れてしまった。", korean: "그의 주소를 잊어버렸다."),
    "体": .init(japanese: "今朝は体の調子がよい。", korean: "오늘 아침은 몸의 상태가 좋다."),
    "使う": .init(japanese: "何に使うの？", korean: "뭐에 쓰려고?"),
    "働く": .init(japanese: "私は日曜日に働く。", korean: "나는 일요일에 일한다."),
    "冷蔵庫": .init(japanese: "冷蔵庫に卵いくつある？", korean: "냉장고에 계란 얼마나 있어?"),
    "危険": .init(japanese: "それでは君が危険になる。", korean: "그러면 네가 위험해져."),
    "台風": .init(japanese: "かなり多くの家が台風で壊された。", korean: "꽤 많은 집이 태풍으로 부서졌다."),
    "喜ぶ": .init(japanese: "彼らはとても喜ぶでしょう。", korean: "그들은 매우 기뻐할 것입니다."),
    "図書館": .init(japanese: "友達は図書館に勉強するために来ます。", korean: "친구는 도서관에 공부하러 와요"),
    "場合": .init(japanese: "火事の場合には１１９番すべきです。", korean: "화재의 경우에는 119를 불러야 합니다."),
    "場所": .init(japanese: "この場所に？", korean: "여기서요?"),
    "声": .init(japanese: "君の声が聞こえる。", korean: "너의 목소리가 들려"),
    "変化": .init(japanese: "人々は変化を恐れる。", korean: "사람들은 변화를 두려워한다."),
    "宿題": .init(japanese: "宿題は自分でやりなさい。", korean: "숙제는 스스로 하세요."),
    "庭": .init(japanese: "猫が庭で遊んでいます。", korean: "고양이가 정원에서 놀고 있습니다."),
    "必要": .init(japanese: "行く必要はないよ。", korean: "갈 필요는 없어."),
    "思う": .init(japanese: "勝つと思う？", korean: "이길 거라 생각해?"),
    "怪我": .init(japanese: "怪我で血が流れた。", korean: "상처에서 피가 흘렀다."),
    "情報": .init(japanese: "その情報は口コミで瞬く間に知れ渡った。", korean: "그 정보는 입소문으로 한 순간에 알려졌다."),
    "意味": .init(japanese: "この文って、どういう意味？", korean: "이 문장은 무슨 뜻이야?"),
    "成功": .init(japanese: "あの働き者の少年の成功は約束されている。", korean: "그 부지런한 소년의 성공은 약속돼있다."),
    "我慢": .init(japanese: "彼らの我慢も限界だった。", korean: "그들의 인내심도 한계였다."),
    "払う": .init(japanese: "税金を払うのは厄介です。", korean: "세금을 내는 것은 귀찮습니다."),
    "授業": .init(japanese: "授業は午前８時３０分に始まる。", korean: "수업은 오전 8시 30분에 시작한다."),
    "文法": .init(japanese: "ドイツ語の文法に手こずっています。", korean: "독일어 문법에 어려움을 겪고 있습니다."),
    "普通": .init(japanese: "レイラはごく普通の１５歳の女の子だった。", korean: "라일라는 매우 평범한 15세 여자아이였다."),
    "最初": .init(japanese: "最初は難しいんだよ。", korean: "처음은 어려운 거야."),
    "最後": .init(japanese: "最後に話をしたのはいつだろうか？", korean: "우리 마지막으로 언제 이야기했더라?"),
    "最近": .init(japanese: "それは最近の写真？", korean: "이 사진 최근 거에요?"),
    "歩く": .init(japanese: "車があるのにどうして歩くの？", korean: "차가 있는데 왜 걸어야 돼?"),
    "歴史": .init(japanese: "歴史には全く興味がないんだ。", korean: "역사에는 전혀 흥미가 없어."),
    "比較": .init(japanese: "同じ縮尺での比較です。", korean: "같은 축척에서의 비교입니다."),
    "気分": .init(japanese: "最悪の気分！", korean: "최악의 기분"),
    "気持ち": .init(japanese: "彼は少しも他人の気持ちを大事にしない。", korean: "그는 타인의 기분은 전혀 존중하지 않는다."),
    "泳ぐ": .init(japanese: "私は彼女が泳ぐのを見た。", korean: "나는 그녀가 헤엄치는 것을 봤다."),
    "準備": .init(japanese: "準備をするためにもっと時間が必要だ。", korean: "좀더 준비할 시간이 필요해."),
    "漢字": .init(japanese: "漢字、何個覚えた？", korean: "한자 몇개 외웠어?"),
    "火事": .init(japanese: "火事の場合には１１９番すべきです。", korean: "화재의 경우에는 119를 불러야 합니다."),
    "無理": .init(japanese: "怖くてそれは無理。", korean: "무서워서 그건 못하겠어."),
    "熱": .init(japanese: "風邪をひいて熱がある。", korean: "감기에 걸려서 열이 나."),
    "病気": .init(japanese: "彼が休んだのは病気のためだ。", korean: "그가 쉰 것은 병 때문이다."),
    "目的": .init(japanese: "彼女は目的を達成した。", korean: "그녀는 목적을 달성했다."),
    "社会": .init(japanese: "社会が変化している。", korean: "사회가 변화하고 있다."),
    "窓": .init(japanese: "彼は窓を壊した。", korean: "그는 창문을 망가뜨렸다."),
    "簡単": .init(japanese: "その本は簡単です。", korean: "그 책은 간단합니다."),
    "約束": .init(japanese: "約束は守るよ。", korean: "약속은 지킬게."),
    "給料": .init(japanese: "私の給料は３０万円だ。", korean: "내 월급은 30만엔이다."),
    "習う": .init(japanese: "なんでフランス語を習うのやめたの？", korean: "왜 프랑스어를 배우는 걸 그만 뒀어?"),
    "自由": .init(japanese: "何でもご自由に召し上がってください。", korean: "먹고 싶은 것들 마음껏 먹어."),
    "興味": .init(japanese: "それにも興味がある。", korean: "그것에도 흥미가 있다."),
    "薬": .init(japanese: "薬の効き目がだんだんなくなってきた。", korean: "약의 효과가 점점 없어지기 시작했다."),
    "見つける": .init(japanese: "私の家を見つけるの、大変だった？", korean: "우리 집을 찾는 거, 힘들었어?"),
    "規則": .init(japanese: "トムは規則を知らない。", korean: "톰은 규칙을 몰라."),
    "覚える": .init(japanese: "トムはしばしば物を覚えるのに苦労する。", korean: "톰은 종종 무언가를 외우는 데에 고생한다."),
    "言う": .init(japanese: "忘れたって言うの？", korean: "잊었다고 말하는 거야?"),
    "言葉": .init(japanese: "今必要なのは言葉ではなく行動だ。", korean: "지금 필요한 건 말이 아닌 행동이다."),
    "計画": .init(japanese: "彼は計画を実行した。", korean: "그는 계획을 실행했다."),
    "試験": .init(japanese: "試験、絶対に合格しろよ。", korean: "시험 무조건 합격해."),
    "財布": .init(japanese: "財布をなくしたの。", korean: "지갑을 잃어버렸어."),
    "質問": .init(japanese: "彼は質問に答えた。", korean: "그는 질문에 대답했다"),
    "趣味": .init(japanese: "水泳は私の趣味です。", korean: "제 취미는 수영입니다."),
    "返事": .init(japanese: "手紙の返事をお忘れなく。", korean: "편지에 답장하는 것을 잊지 않도록."),
    "途中": .init(japanese: "学校へ行く途中でトムに会った。", korean: "학교에가는 도중에 톰 만났다."),
    "連絡": .init(japanese: "これからも連絡を取り合いましょうね。", korean: "앞으로도 서로 연락하고 지내요."),
    "鉛筆": .init(japanese: "あれは鉛筆です。", korean: "그거 연필이야"),
    "門": .init(japanese: "門の前で待つよ。", korean: "문 앞에서 기다릴께."),
    "閉める": .init(japanese: "ドアをバタンと閉めるのはよせ。", korean: "문을 세게 닫는 건 그만 둬."),
    "間に合う": .init(japanese: "彼は列車に間に合うでしょうか。", korean: "그는 열차에 제때 탈 수 있을까요?"),
    "関係": .init(japanese: "彼は例のスキャンダルと関係があると思う。", korean: "그는 여느 스캔들과 관계가 있다고 생각해."),
    "集める": .init(japanese: "僕たちは全世界の切手を集める。", korean: "우리는 전 세계의 우표를 모은다."),
    "頭": .init(japanese: "頭が痛い。", korean: "나 머리 아파."),
    "顔": .init(japanese: "トム、どうしたの？顔が真っ赤っ赤だけど。", korean: "왜 그래, 톰? 얼굴이 새빨간데."),
    "風邪": .init(japanese: "風邪ですね。", korean: "감기네요."),
]
